redis:
  image: amtrak_redis
  hostname: amtrak_redis
  volumes:
    - "./redis:/data"
tracelyzer:
  image: tracelyzer
  hostname: amtrak_tracelyzer
web:
  image: amtrak_endpoint
  hostname: amtrak_endpoint
  links:
    - redis
    - tracelyzer
  volumes_from:
    - tracelyzer
  command: unicorn
nginx:
  image: nginx_oboe
  hostname: amtrak_nginx
  links:
    - tracelyzer
    - web
  volumes:
    - "./nginx:/opt/nginx/config"
  volumes_from:
    - tracelyzer
    - web
  ports:
    - "8080:8080"
